### ISSUE TITLE
[solved] Incompatible with node-redis v5 - pttl is not a function

### ISSUE THREAD

**Issue by uuyaniksoy** [animir/node-rate-limiter-flexible#346]
When we upgrade node-redis from 4.6.13 to the latest version 5.10.0, `RateLimiterRedis.get()` started to throw the following error: ```TypeError: this.client.multi(...).get(...).pttl is not a function```
This was working as expected before the upgrade. I've tried upgrading `rate-limiter-flexible` as well but the issue persists.

Could you please provide a fix for this issue? We would like to upgrade our node-redis version to the latest.

**Versions:** rate-limiter-flexible 8.2.1 / 9.0.1, node-redis 5.10.0, Node.js 20.x
